alter table utilisateurs 
modify utilisateur_id 
generated by default on null as identity (
    start with limit value
);

alter table Besoin_Realiser 
modify besoin_rea_id
generated by default on null as identity(
    start with limit value
);

alter table  Recommendations
modify recomm_id
generated by default on null as identity(
    start with limit value
);

alter table Candidatures
modify candidature_id
generated by default on null as identity(
    start with limit value
);

alter table Publications
modify publication_id
generated by default on null as identity(
    start with limit value
);
 
 alter table Besoins
modify besoin_id
generated by default on null as identity(
    start with limit value
);
