 PROMPT INSERTING into Besions
set define off 
begin
insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (1,'besion d un plombier','semaine','Douala',4,'PLOMB');

insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (2,'besion d un Majeur d homme','mois','Douala',2,'DOMES');

insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (3,'besion d un Jardinier','jour','Yaounde',3,'JARD');

insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (4,'besion d un chauffeur','mois','Douala',1,'TRANS');

insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (5,'besion d un gardien','semaine','Douala',5,'SECUR');

insert into Besoins (besoin_id,besoin_description,payement_par,localisation,utilisateur_id,secteur_id)
values (6,'besion d une Menagere','semaine','Douala',3,'DOMES');


end;
/
-- CREATE TABLE Besoins(
--     besoin_id integer generated by default on null as identity,
--     besoin_description VARCHAR(40),
--     payement_par VARCHAR(45),
--     localisation VARCHAR(25),
--     utilisateur_id integer not null,
--     secteur_id integer not null
-- );