 PROMPT INSERTING into Candidatures
set define off 
begin
insert into Candidatures(candidature_id,candidature_date,candidature_statut,proposition,publication_id,utilisateur_id,besoin_rea_id)
values (1,to_date('10/12/2021','DD/MM/YYYY'),'En attente',10000,2,3,1);

insert into Candidatures(candidature_id,candidature_date,candidature_statut,proposition,publication_id,utilisateur_id,besoin_rea_id)
values (2,to_date('10/03/2021','DD/MM/YYYY'),'Rejete',15000,4,2,3);

insert into Candidatures(candidature_id,candidature_date,candidature_statut,proposition,publication_id,utilisateur_id,besoin_rea_id)
values (3,to_date('06/12/2021','DD/MM/YYYY'),'Accepete',5000,3,5,5);

insert into Candidatures(candidature_id,candidature_date,candidature_statut,proposition,publication_id,utilisateur_id,besoin_rea_id)
values (4,to_date('10/12/2021','DD/MM/YYYY'),'Accepete',10000,1,4,6);

insert into Candidatures(candidature_id,candidature_date,candidature_statut,proposition,publication_id,utilisateur_id,besoin_rea_id)
values (5,to_date('10/12/2021','DD/MM/YYYY'),'En attente',10000,5,1,2);

end;
/

-- CREATE TABLE Candidatures(
--     candidature_id integer generated by default on null as identity,
--     candidature_date DATE,
--     candidature_statut VARCHAR(10) NOT NULL,
--     proposition FLOAT,
--     publication_id integer not null,
--     utilisateur_id integer not null,
--     besoin_rea_id integer not null
-- );