 PROMPT INSERTING into Publications
set define off 
begin

insert into Publications(publication_id,publication_date,publication_statut,salaire,duree,description,besoin_id)
values (1,to_date('05/08/2021','DD/MM/YYYY'),'Ouvert','20000fcfa','02 mois','besoin d une menagere',1);

insert into Publications(publication_id,publication_date,publication_statut,salaire,duree,description,besoin_id)
values (2,to_date('05/05/2021','DD/MM/YYYY'),'Fermer','15000fcfa','02 mois','besoin d un jardinier',2);

insert into Publications(publication_id,publication_date,publication_statut,salaire,duree,description,besoin_id)
values (3,to_date('05/12/2021','DD/MM/YYYY'),'Ouvert','80000fcfa','02 mois','besoin d une gardien',3);

insert into Publications(publication_id,publication_date,publication_statut,salaire,duree,description,besoin_id)
values (4,to_date('05/09/2021','DD/MM/YYYY'),'Fermer','17000fcfa','02 mois','besoin d un chauffeur',4);

insert into Publications(publication_id,publication_date,publication_statut,salaire,duree,description,besoin_id)
values (5,to_date('05/03/2021','DD/MM/YYYY'),'Ouvert','60000fcfa','02 mois','besoin d un plombier',5);



end;
/

-- CREATE TABLE Publications(
--     publication_id integer generated by default on null as identity,
--     publication_date Date,
--     publication_statut VARCHAR(10) NOT NULL,
--     salaire VARCHAR(10),
--     duree VARCHAR(10),
--     description VARCHAR(40),
--     besoin_id integer not null 
-- );