 PROMPT INSERTING into Recommendations 
set define off 
begin

insert into Recommendations(recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (1,'John','699740025','jok651@gmail.com','il est bon','Confirme',2);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (2,'Clement Bourigeo','68912625','clement51@gmail.com','il est bon','Confirme',5);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (3,'RnamDev','690209967','rnamDev@gmail.com','il est bon','Confirme',1);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (4,'Ebonke','655689547','Ebonke@gmail.com','il est bon','Rejete',3);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (5,'Wapalu','67778547','Wapalu@gmail.com','il est bon','Confirme',7);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (6,'Calvin','677485025','calgoo@gmail.com','il est mauvais','Confirme',8);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (7,'Pouani','685471256','latrant@gmail.com','il est passable','Rejete',4);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (8,'Kolo muani','65641236','Kolo@gmail.com','il est passable','Rejete',9);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (9,'Mbappe','699821400','kylian@gmail.com','il est mauvzis','Rejete',10);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (10,'Jack','687740025','jff@gmail.com','il est bon','Confirme',11);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (11,'Tobi','696780045','goupr@gmail.com','il est tres bon','Confirme',12);

insert into Recommendations (recomm_id,recomm_nom,recomm_numero,recomm_email,recomm_contenue,recomm_statut,utilisateur_id)
values (12,'Ange','69956425','joAnge@gmail.com','il est bon','Confirme',6);
end;
/

-- CREATE TABLE Recommendations(
--     recomm_id integer generated by default on null as identity,
--     recomm_nom VARCHAR(45) NOT NULL,
--     recomm_numero VARCHAR(45) NOT NULL,
--     recomm_email recomm_contenue,VARCHAR(45) NOT NULL,
--     recomm_contenue VARCHAR(45) NOT NULL,
--     recomm_statut VARCHAR(10),
--     utilisateur_id int NOT NULL
--  );